apiVersion: v1
kind: Plugin
metadata:
  author: sheetung
  name: LangBotPluginBox
  repository: https://github.com/sheetung/LangBotPluginBox
  version: 0.7.1
  description:
    en_US: LangBot some small plugins
    zh_Hans: Lang一些小功能插件集合
  label:
    en_US: LangBotPluginBox
    zh_Hans: LangBotPluginBox
  icon: assets/icon.png
spec:
  config:
    - name: boxadmin_id_
      type: string
      label:
        en_US: 'Admin QQ'
        zh_Hans: '管理员QQ'
      required: true
      default: '' 
  components:
    EventListener:
      fromDirs:
      - path: components/event_listener/
execution:
  python:
    path: main.py
    attr: LangBotPluginBox
