apiVersion: v1
kind: Plugin
metadata:
  author: sheetung
  name: LangBotPluginBox
  repository: https://github.com/sheetung/LangBotPluginBox
  version: 0.8.9
  description:
    en_US: LangBot some small plugins
    zh_Hans: Lang一些小功能插件集合
  label:
    en_US: LangBotPluginBox
    zh_Hans: LangBotPluginBox
  icon: assets/icon.png
spec:
  config:
    - name: boxadmin_id
      type: string
      label:
        en_US: 'Admin QQ'
        zh_Hans: '管理员QQ'
      required: true
      default: ''
    - name: weather_key
      type: string
      label:
        en_US: 'Weather API Key'
        zh_Hans: '和风天气API密钥，[链接](https://console.qweather.com/home?lang=zh)'
      required: true
      default: ''
    - name: menu_url
      type: string
      label:
        en_US: 'Menu image URL'
        zh_Hans: '菜单命令图片展示URL'
      required: false
      default: ''
  components:
    EventListener:
      fromDirs:
      - path: components/event_listener/
execution:
  python:
    path: main.py
    attr: LangBotPluginBox
