apiVersion: v1
kind: Plugin
metadata:
  author: sheetung
  name: LangBotPluginBox
  repository: https://github.com/sheetung/LangBotPluginBox
  version: 0.4.1
  description:
    en_US: LangBot some small plugins
    zh_Hans: Lang一些小功能插件集合
  label:
    en_US: LangBotPluginBox
    zh_Hans: LangBot插件盒子
  icon: assets/icon.png
spec:
  config: []
  components:
    EventListener:
      fromDirs:
      - path: components/event_listener/
execution:
  python:
    path: main.py
    attr: LangBotPluginBox
